#ifndef CONFIG_H
#define CONFIG_H

#define SERIAL_MONITOR_BAUD_RATE 115200

#define RADIO_TX_PIN 17
#define RADIO_RX_PIN 18

#define RX_BUFFER_SIZE 512

#define FLOAT_PRECISION 4
#define GPS_PRECISION 6

#define USB_COMMAND_WRAPPER_SIZE 8
#define USB_COMMAND_WRAPPER_TERMINATOR 0x88 // Confirm with python files

#endif
