"""Shared constants: command codes, serial packet framing, and telemetry field layout."""

from enum import IntEnum


class CommandType(IntEnum):
    ENTER_CONFIG = 0
    EXIT_CONFIG = 1
    SET_THRUST_SCALE = 2
    SET_THRUST_OFFSET = 3
    TARE_THRUST = 4
    CALIBRATE_THRUST = 5
    SET_OXIDIZER_LOADCELL_SCALE = 6
    SET_OXIDIZER_LOADCELL_OFFSET = 7
    TARE_OXIDIZER_LOADCELL = 8
    CALIBRATE_OXIDIZER_LOADCELL = 9
    SET_FUEL_PRESSURE_SCALE = 10
    SET_FUEL_PRESSURE_OFFSET = 11
    SET_OXIDIZER_PRESSURE_SCALE = 12
    SET_OXIDIZER_PRESSURE_OFFSET = 13
    TARE_PRESSURE = 14
    CALIBRATE_FUEL_PRESSURE = 15
    CALIBRATE_OXIDIZER_PRESSURE = 16
    DUMP_FLASH = 17


# --- Outgoing command packet framing ---
PACKET_START_BYTE_1 = 0xCC
PACKET_START_BYTE_2 = 0x77
PACKET_END_BYTE = 0x88
PACKET_PAYLOAD_LENGTH = 4
DEFAULT_PAYLOAD = b"\x00\x00\x00\x00"

# --- Incoming telemetry packet field indices (semicolon-delimited line) ---
class TelemetryField(IntEnum): 
    TIMESTAMP_MS = 0
    TELEMETRY_FRAME_INDEX = 1
    ACCELERATION_MAIN_X = 2
    ACCELERATION_MAIN_Y = 3
    ACCELERATION_MAIN_Z = 4
    ANGULAR_VELOCITY_X = 5
    ANGULAR_VELOCITY_Y = 6
    ANGULAR_VELOCITY_Z = 7
    ACCELERATION_HIGH_G_X = 8
    ACCELERATION_HIGH_G_Y = 9
    ACCELERATION_HIGH_G_Z = 10
    AIR_PRESSURE = 11
    AIR_TEMPERATURE = 12
    ALTITUDE_FUSION = 13
    ENGINE_THRUST = 14
    OXIDIZER_WEIGHT = 15
    FUEL_PRESSURE = 16
    OXIDIZER_PRESSURE = 17
    PYRO_BATTERY_VOLTAGE = 18
    MAIN_BATTERY_VOLTAGE = 19
    ENGINE_TEMPERATURE_TOP = 20
    ENGINE_TEMPERATURE_BOTTOM = 21
    PISTON_POSITION = 22
    LATITUDE = 23
    LONGITUDE = 24
    ALTITUDE_GPS = 25
    SATTELITE_COUNT = 26
    MAIN_BATTERY_LEVEL = 27
    IS_VALID_BIT_MASK = 28
    CURRENT_FLIGHT_PHASE = 29
    CURRENT_ARM_STATE = 30
    LAST_COMMAND_FRAME_INDEX = 31
    LAST_COMMAND_RESULT = 32
    RECEIVED_FRAME_COUNT = 33
    INVALID_FRAME_COUNT = 34
    MISSING_FRAME_COUNT = 35

# --- Serial / UI timing ---
DEFAULT_BAUDRATE = 115200
SERIAL_POLL_INTERVAL_MS = 5
PLOT_REFRESH_INTERVAL_MS = 33  # ~30 Hz
THRUST_BUFFER_MAXLEN = 2000
